# Generated by Django 2.0.5 on 2018-05-12 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
